const seeder = require("mongoose-seed");
const db = require("./config/keys").mongoURI;
const bcrypt = require("bcryptjs");

// Connect to MongoDB
seeder.connect(db, () => {
  // Load Mongoose models
  seeder.loadModels([
    "./models/User.js",
    "./models/Block.js",
    "./models/Track.js",
    "./models/Vote.js",
  ]);

  // Clear specified collections
  seeder.clearModels(["User", "Block", "Track", "Vote"], () => {
    // Callback to poplulate DB once models are cleared
    seeder.populateModels(data, () => {
      seeder.disconnect();
    });
  });
});

// bcrypt demo user password
const salt = bcrypt.genSaltSync(10);
const hash = bcrypt.hashSync("password", salt);

// Populate demo user and block templates
const data = [
  {
    model: "User",
    documents: [
      {
        handle: "demouser",
        email: "demouser@gmail.com",
        password: hash,
      },
    ],
  },
  {
    model: "Block",
    documents: [
      {
        idx: 0,
        note: "C4",
        duration: "4n",
        width: 100,
        height: 25,
        color: "#AF3508",
      },
      {
        idx: 1,
        note: "C#4",
        duration: "4n",
        width: 100,
        height: 26,
        color: "#AF3508",
      },
      {
        idx: 2,
        note: "D4",
        duration: "4n",
        width: 100,
        height: 27,
        color: "#C64E1B",
      },
      {
        idx: 3,
        note: "D#4",
        duration: "4n",
        width: 100,
        height: 28,
        color: "#C64E1B",
      },
      {
        idx: 4,
        note: "E4",
        duration: "4n",
        width: 100,
        height: 29,
        color: "#DD662E",
      },
      {
        idx: 5,
        note: "F4",
        duration: "4n",
        width: 100,
        height: 30,
        color: "#E98440",
      },
      {
        idx: 6,
        note: "F#4",
        duration: "4n",
        width: 100,
        height: 31,
        color: "#E98440",
      },
      {
        idx: 7,
        note: "G4",
        duration: "4n",
        width: 100,
        height: 32,
        color: "#F5A151",
      },
      {
        idx: 8,
        note: "G#4",
        duration: "4n",
        width: 100,
        height: 33,
        color: "#F5A151",
      },
      {
        idx: 9,
        note: "A4",
        duration: "4n",
        width: 100,
        height: 34,
        color: "#F5A951",
      },
      {
        idx: 10,
        note: "A#4",
        duration: "4n",
        width: 100,
        height: 35,
        color: "#F5A951",
      },
      {
        idx: 11,
        note: "B4",
        duration: "4n",
        width: 100,
        height: 36,
        color: "#F4B150",
      },
      {
        idx: 12,
        note: "C5",
        duration: "4n",
        width: 100,
        height: 37,
        color: "#E6B775",
      },
      {
        idx: 13,
        note: "C#5",
        duration: "4n",
        width: 100,
        height: 38,
        color: "#E6B775",
      },
      {
        idx: 14,
        note: "",
        duration: "4n",
        width: 100,
        height: 39,
        color: "black",
      },
      {
        idx: 15,
        note: "C4",
        duration: "8n",
        width: 50,
        height: 50,
        color: "#1E6E37",
      },
      {
        idx: 16,
        note: "C#4",
        duration: "8n",
        width: 50,
        height: 51,
        color: "#1E6E37",
      },
      {
        idx: 17,
        note: "D4",
        duration: "8n",
        width: 50,
        height: 52,
        color: "#138A36",
      },
      {
        idx: 18,
        note: "D#4",
        duration: "8n",
        width: 50,
        height: 53,
        color: "#138A36",
      },
      {
        idx: 19,
        note: "E4",
        duration: "8n",
        width: 50,
        height: 54,
        color: "#10A232",
      },
      {
        idx: 20,
        note: "F4",
        duration: "8n",
        width: 50,
        height: 55,
        color: "#0CB92D",
      },
      {
        idx: 21,
        note: "F#4",
        duration: "8n",
        width: 50,
        height: 56,
        color: "#0CB92D",
      },
      {
        idx: 22,
        note: "G4",
        duration: "8n",
        width: 50,
        height: 57,
        color: "#04E824",
      },
      {
        idx: 23,
        note: "G#4",
        duration: "8n",
        width: 50,
        height: 58,
        color: "#04E824",
      },
      {
        idx: 24,
        note: "A4",
        duration: "8n",
        width: 50,
        height: 59,
        color: "#0EF449",
      },
      {
        idx: 25,
        note: "A#4",
        duration: "8n",
        width: 50,
        height: 60,
        color: "#0EF449",
      },
      {
        idx: 26,
        note: "B4",
        duration: "8n",
        width: 50,
        height: 61,
        color: "#18FF6D",
      },
      {
        idx: 27,
        note: "C5",
        duration: "8n",
        width: 50,
        height: 62,
        color: "#85FFB1",
      },
      {
        idx: 28,
        note: "C#5",
        duration: "8n",
        width: 50,
        height: 63,
        color: "#85FFB1",
      },
      {
        idx: 29,
        note: "",
        duration: "8n",
        width: 50,
        height: 64,
        color: "black",
      },
      {
        idx: 30,
        note: "C4",
        duration: "16n",
        width: 25,
        height: 100,
        color: "#031A6B",
      },
      {
        idx: 31,
        note: "C#4",
        duration: "16n",
        width: 25,
        height: 101,
        color: "#031A6B",
      },
      {
        idx: 32,
        note: "D4",
        duration: "16n",
        width: 25,
        height: 102,
        color: "#182288",
      },
      {
        idx: 33,
        note: "D#4",
        duration: "16n",
        width: 25,
        height: 103,
        color: "#182288",
      },
      {
        idx: 34,
        note: "E4",
        duration: "16n",
        width: 25,
        height: 104,
        color: "#2C29A4",
      },
      {
        idx: 35,
        note: "F4",
        duration: "16n",
        width: 25,
        height: 105,
        color: "#5438DC",
      },
      {
        idx: 36,
        note: "F#4",
        duration: "16n",
        width: 25,
        height: 106,
        color: "#5438DC",
      },
      {
        idx: 37,
        note: "G4",
        duration: "16n",
        width: 25,
        height: 107,
        color: "#4D4AE1",
      },
      {
        idx: 38,
        note: "G#4",
        duration: "16n",
        width: 25,
        height: 108,
        color: "#4D4AE1",
      },
      {
        idx: 39,
        note: "A4",
        duration: "16n",
        width: 25,
        height: 109,
        color: "#455BE5",
      },
      {
        idx: 40,
        note: "A#4",
        duration: "16n",
        width: 25,
        height: 110,
        color: "#455BE5",
      },
      {
        idx: 41,
        note: "B4",
        duration: "16n",
        width: 25,
        height: 111,
        color: "#357DED",
      },
      {
        idx: 42,
        note: "C5",
        duration: "16n",
        width: 25,
        height: 112,
        color: "#4789EF",
      },
      {
        idx: 43,
        note: "C#5",
        duration: "16n",
        width: 25,
        height: 113,
        color: "#4789EF",
      },
      {
        idx: 44,
        note: "",
        duration: "16n",
        width: 25,
        height: 114,
        color: "black",
      },
    ],
  },
];
